### ISSUE TITLE
Bad link for downloading  Hyperledger Fabric binaries and Docker images

### ISSUE THREAD

**Issue by waygee** [CATechnologies/blockchain-tutorials#3]
curl -sSL https://goo.gl/fMh2s3 | bash

results in a 404 error

**Comment by waygee** [comment]
I used this link instead:  

curl -sSL https://goo.gl/6wtTN5 | bash 

I will continue with the installation and see if it works.

**Comment by waygee** [comment]
Ok, yes it worked fine with the new link provided above

**Comment by PetrVlasek** [comment]
Thank you for reporting broken link. It is changed to v1.2 assets link,

**Comment by PetrVlasek** [comment]
Thank you for reporting this issue with broken link. It is now changed to point to v1.2 assets.
